/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TillRouteImport } from './routes/till'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'

const TillRoute = TillRouteImport.update({
  id: '/till',
  path: '/till',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/assistant': typeof AssistantRoute
  '/insights': typeof InsightsRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRoute
  '/orders': typeof OrdersRoute
  '/sale': typeof SaleRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/till': typeof TillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/assistant': typeof AssistantRoute
  '/insights': typeof InsightsRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRoute
  '/orders': typeof OrdersRoute
  '/sale': typeof SaleRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/till': typeof TillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/assistant': typeof AssistantRoute
  '/insights': typeof InsightsRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRoute
  '/orders': typeof OrdersRoute
  '/sale': typeof SaleRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/till': typeof TillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/assistant'
    | '/insights'
    | '/inventory'
    | '/locations'
    | '/orders'
    | '/sale'
    | '/settings'
    | '/staff'
    | '/till'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/assistant'
    | '/insights'
    | '/inventory'
    | '/locations'
    | '/orders'
    | '/sale'
    | '/settings'
    | '/staff'
    | '/till'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/assistant'
    | '/insights'
    | '/inventory'
    | '/locations'
    | '/orders'
    | '/sale'
    | '/settings'
    | '/staff'
    | '/till'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AssistantRoute: typeof AssistantRoute
  InsightsRoute: typeof InsightsRoute
  InventoryRoute: typeof InventoryRoute
  LocationsRoute: typeof LocationsRoute
  OrdersRoute: typeof OrdersRoute
  SaleRoute: typeof SaleRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  TillRoute: typeof TillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/till': {
      id: '/till'
      path: '/till'
      fullPath: '/till'
      preLoaderRoute: typeof TillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AssistantRoute: AssistantRoute,
  InsightsRoute: InsightsRoute,
  InventoryRoute: InventoryRoute,
  LocationsRoute: LocationsRoute,
  OrdersRoute: OrdersRoute,
  SaleRoute: SaleRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  TillRoute: TillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
